

import type React from "react";
import type { Metadata } from "next";

import "./globals.css";

import ClientLayout from "./clientLayout";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
 
      >
        <ClientLayout>
          {/* <Navbar /> */}
          {children}
          {/* <Footer /> */}
        </ClientLayout>
      </body>
    </html>
  );
}
